### ISSUE TITLE
ESCRIBIR FECHAS COTIZADOR

### ISSUE THREAD

**Issue by SANTIAGOOLANO** [Fedea-SA/spiga-issues#19]
Se debería poder escribir de manera rapida e intuitiva una fecha (ej vencimiento de la cotización en la linea del art en particular), un ejemplo puede ser nautilus que se escribe de corrido sin las barras que separan dia de mes de año. En este caso yo solo pude colocar la fecha seleccionando en el almanaque q se despliega.

**Comment by awaltersierra** [comment]
Resuelto, vamos a trabajar para poner a disposición una nueva versión con estos cambios
