### ISSUE TITLE
Cotizador - Falta Unidades de Negocios

### ISSUE THREAD

**Issue by MartinOE279** [Fedea-SA/spiga-issues#21]
- [ ] No aparece el desplegable de las unidades de negocios al ingresar un cliente nuevo.
![Unidades de Negocios](https://github.com/Fedea-SA/grow-issues/assets/172398072/a33d244a-004f-431b-821d-cb6274dded47)

**Comment by alanmdza** [comment]
El desplegable debe estar cerrado, haciendole click lo puedes abrir de nuevo 


![image](https://github.com/Fedea-SA/grow-issues/assets/153772944/0f9e4187-83c5-403d-85dc-ab5f5d32a6f3)
