### ISSUE TITLE
Cotizador Combustibles - Fecha de Vencimiento

### ISSUE THREAD

**Issue by MartinOE279** [Fedea-SA/spiga-issues#23]
- [x] Luego de elegir la Condición de Pago (en este caso SGR), cuando quiero colocar la Fecha de Pago me indica que no puede ser menor al 10 de Mayo de 2024. 
- [x] Si igualmente pongo una fecha inferior al 10 de Mayo de 2024, luego no me deja colocar el Precio. 
![FECHA DE PAGO](https://github.com/Fedea-SA/grow-issues/assets/172398072/fc22d966-00c2-484a-b93a-67f9bfd9d52d)
![PRECIO](https://github.com/Fedea-SA/grow-issues/assets/172398072/d711d045-78e1-491b-8680-51698f2c77f3)

**Comment by awaltersierra** [comment]
Martin, lo que esta pasando es que Pablo Alvarez deberia RE-Parametrizar los elementos de Pago, igualmente estamos agregando un control que te permita cotizar con un elemento fuera de su fecha de vigencia pero que te alerte de lo que esta sucediendo.
