### ISSUE TITLE
Reunion Nutri

### ISSUE THREAD

**Issue by FranSLab** [Fedea-SA/spiga-issues#8]
- [x] Ver formula de calculo de cotizacion. Articulo CONCENTRADO 10% NOVI.PESADO C/BRB (Bls).
- [x] Filtro de condiciones comerciales, el primer filtro (UN) no filtra el segundo (PRODUCTO).
- [x] Margen y descuento en %.
- [x] Reveer filtros de condiciones de pago en cotizaciones, en algunos casos no trae (tarjeta).
- [x] Agregar unidad en condiciones comerciales y items de la cotizacion.

**Comment by awaltersierra** [comment]
[] NombreApellido en Vendedores, le falta un espacio
